# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b087d99012814ff6a7832cf8a90ebf4e56b63d27a4382ad54c0b206060119c113f45a3aaed8c5e016caa350bdaaa37097a7b27c6a2d27e0387fcb8f99ff6c30c

test:
  secret_key_base: 7dc95a74944f6c44021bd3230749206b72b93c667b803d27923f4d4ad17794cacdbc49fdb7b80b57035d2bf2a6503dcf486b34e9d4b3889c783b1dfa1cc724cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
